/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmBtn: typeof import('./src/components/ConfirmBtn.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    LoginView: typeof import('./src/views/LoginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TitleBar: typeof import('./src/layout/user/TitleBar.vue')['default']
    UserAbout: typeof import('./src/views/user/UserAbout.vue')['default']
    UserCheckout: typeof import('./src/views/user/UserCheckout.vue')['default']
    UserHome: typeof import('./src/views/user/UserHome.vue')['default']
    UserLayout: typeof import('./src/layout/user/UserLayout.vue')['default']
    UserMenuSelect: typeof import('./src/layout/user/UserMenuSelect.vue')['default']
    UserPopup: typeof import('./src/components/UserPopup.vue')['default']
    UserSide: typeof import('./src/layout/user/UserSide.vue')['default']
    UserSopping: typeof import('./src/layout/user/UserSopping.vue')['default']
  }
}
